spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: Jwt
          args:
            excludeRoutes:
              - "/api/security-service/security"
      routes:
        - id: user_routes
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/routes/user/**
        - id: user_favorites
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/favorites/user/**
        - id: user_sessions
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/sessions/user/**
        - id: user_reviews
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/reviews/user/**

        - id: admin_routes
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/routes/admin/**
        - id: admin_favorites
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/favorites/admin/**
        - id: admin_sessions
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/sessions/admin/**
        - id: admin_reviews
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/reviews/admin/**

        - id: admin_metrics
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/metrics/admin/**

        - id: security
          uri: http://${DEV_ENV_HOST_SECURITY}:8082
          predicates:
            - Path=/api/security-service/security/**

        - id: photos
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/photos/**

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints.web.exposure.include: 'prometheus, health, info, metrics'
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true