spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: Jwt
          args:
            excludeRoutes:
              - "/api/security-service/security"
              - "/v3/api-docs/data-provider"
              - "/v3/api-docs/security-service"
      routes:
        - id: user_routes
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/routes/user/**
        - id: user_favorites
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/favorites/user/**
        - id: user_sessions
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/sessions/user/**
        - id: user_reviews
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/reviews/user/**

        - id: admin_routes
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/routes/admin/**
        - id: admin_favorites
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/favorites/admin/**
        - id: admin_sessions
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/sessions/admin/**
        - id: admin_reviews
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/reviews/admin/**

        - id: admin_metrics
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/metrics/admin/**

        - id: security
          uri: http://${DEV_ENV_HOST_SECURITY}:8082
          predicates:
            - Path=/api/security-service/security/**

        - id: photos
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/api/data-provider/photos/**

        - id: data-provider-api-docs
          uri: http://${DEV_ENV_HOST_PROVIDER}:8081
          predicates:
            - Path=/v3/api-docs/data-provider
          filters:
            - RewritePath=/v3/api-docs/data-provider,/v3/api-docs

        - id: security-service-api-docs
          uri: http://${DEV_ENV_HOST_SECURITY}:8082
          predicates:
            - Path=/v3/api-docs/security-service
          filters:
            - RewritePath=/v3/api-docs/security-service, /v3/api-docs

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints.web.exposure.include: 'prometheus, health, info, metrics'
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: data-provider
        url: /v3/api-docs/data-provider
      - name: security-service
        url: /v3/api-docs/security-service
    path: /swagger-ui.html